### ISSUE TITLE
Rtclock

### ISSUE THREAD

**Issue by seprj** [chipsec/chipsec#1632]
Hello @dscott90 
can you help me about Rtclock
In Chipsec, in the rtclock module in python, I know that the third bit of RC register, which is the result of (LL and UL), if only one of them(LL/UL) is 1, causes Rtclock memory not to be locked, how can third bit be always set to 1 through Chipsec and always Rtclock keep locked for ever 
and why this Register sometimes not locked??
Im confused !!
thank you for your guide

**Comment by dscott90** [comment]
Hi @seprj,

The chipsec rtclock module checks the upper and lower lock fields from the RC register to determine whether the platform has locked the real-time clock.

Using the -a switch with the rtclock module will trigger an attempt to modify the CMOS values, but they will be returned to their original values if successfully modified. The chipsec tool cannot force the RTC to stay locked permanently.

Lastly, some platforms may not specify that the RTC needs to be locked, so the chipsec tool reports these occurrances as WARNING instead of FAILED.
