### ISSUE TITLE
CHIPSEC the Windows driver issue

### ISSUE THREAD

**Issue by boxf1** [chipsec/chipsec#251]
Why delete "push rax,rcx,rdx" in drivers/win7/amd64/cpu.asm(_swsmi)?It will cause fuzz test fail.

**Comment by ErikBjorge** [comment]
I have started to look into this again.  We will need to check the calling code to see how it handles the registers.  @andrew-furtak may be able to provide some more information about the change.

**Comment by BrentHoltsclaw** [comment]
Please see: https://docs.microsoft.com/en-us/cpp/build/caller-callee-saved-registers

**Comment by boxf1** [comment]
@andrew-furtak can you help to provide some more information about the change?

**Comment by andrew-furtak** [comment]
According to Windows x64 calling convention registers RAX, RCX, RDX "are considered volatile and must be considered destroyed on function calls". There is no need to save them. You should check the link provided by BrentHoltsclaw.

**Comment by boxf1** [comment]
@andrew-furtak Our some fuzz test will fail when we don't save them, and the test will pass when we save them.

**Comment by BrentHoltsclaw** [comment]
@boxf1 can you provide a verbose log

**Comment by ErikBjorge** [comment]
If you are able to provide a verbose log file as @BrentHoltsclaw suggests we may be able to debug the problem you are seeing.  Can we also get a better description of the failure that you are seeing.  We need to be able to determine if the failure is due to the SMI handler updating the buffer or register corruption.

**Comment by andrew-furtak** [comment]
My guess is SMI handler may change registers we do not preserve. This may lead to a failure. The solution is to save all the non-volatile registers and restore them back on return.

**Comment by ErikBjorge** [comment]
I can update the Windows driver as well as the UEFI Shell code that I just submitted as a pull request to do this.

**Comment by boxf1** [comment]
[0x43.txt](https://github.com/chipsec/chipsec/files/1158382/0x43.txt)

**Comment by ErikBjorge** [comment]
So this may be a real failure.  Can you please run the same test and also include the -v flag so we can verify the buffer values?

The bug that was fixed in the Windows driver was that RSI and RDI were not getting set correctly on the second and third SMI.  This left random values in these registers when generating the SMI instead of the buffer address.  After the fix the registers are being set correctly to point to the buffer and the test can detect any changes that are made by the SMI.

Now that RSI is being set correctly when generating the SMI the test is detecting the failure.

**Comment by boxf1** [comment]
@ErikBjorge Please provide a example of usage for -v.

**Comment by ErikBjorge** [comment]
The -v flag is just added to the existing set of parameters to enable verbose output.  The example below assumes that you are running from source.

python chipsec_main.py -v -m tools.smm.smm_ptr -a fuzz,0x43:0x43 -l 0x43.txt

**Comment by boxf1** [comment]
[43-v.txt](https://github.com/chipsec/chipsec/files/1164094/43-v.txt)

**Comment by andrew-furtak** [comment]
The test failed due to SMI pointer vulnerability present in the firmware. The value from one of the registers holding 0x5A5A5A5A was written to the buffer pointed to by RSI register by the SMI handler. This is exactly what the fuzzer was created for.

**Comment by boxf1** [comment]
How to fix this failure?update the Windows driver?

**Comment by andrew-furtak** [comment]
update the firmware :)

**Comment by andrew-furtak** [comment]
It's not the driver problem. It's a firmware problem.

**Comment by boxf1** [comment]
Do you mean it is BIOS firmware problem?But why we can test pass when we add ""push rax  ,pop rax" in _swsmi (drivers\win7\amd64\cpu.asm)?

**Comment by andrew-furtak** [comment]
I did not just removed push rax, pop rax. I fixed parameters passing. Before the fix only the first 2 parameters had correct values. Because of this the fuzzer just didn't work and could not find the firmware issue you just found.

**Comment by ErikBjorge** [comment]
If you just add a push RAX and a pop RAX in the source you have modified the stack offsets for the parameters that are passed via the stack.  Just adding these instructions without updating the parameter offsets introduces a new bug and RSI will not get set with the correct pointer value.

The change to the driver fixed our generation of SMIs when the pointer is passed in RSI and RDI.  The bug was due to not correctly handling parameter passing.  Because of this fix new failures could be found in system firmware (BIOS).

The log you provided shows the memory modification in the test buffer after generating the particular SMI with the buffer address in RSI.

**Comment by boxf1** [comment]
![cpu_asm](https://user-images.githubusercontent.com/29848793/28499272-98b718f0-6fe4-11e7-9015-5a18ffab2082.jpg)

**Comment by andrew-furtak** [comment]
@box1, adding "push rax" you change the stack pointer. The following code getting the parameters from stack gets wrong values. This is why the test "passes".

**Comment by ErikBjorge** [comment]
@andrew-furtak is correct.  The change you made broke the code and introduced a bug that keeps RDX, RSI and RDI from getting the correct values from the stack.
