### ISSUE TITLE
Unsupport platform

### ISSUE THREAD

**Issue by kamaitachi522** [chipsec/chipsec#343]
ERROR: Unsupported Platform: VID = 0x8086, DID = 0x7190
ERROR: Platform is not supported (Unsupported Platform: VID = 0x8086, DID = 0x7190)

Can you help me fix this error

**Comment by ErikBjorge** [comment]
I will take a look at what it will take to add support for this platform.

**Comment by johnloucaides** [comment]
If you have concerns about chipsec affecting the system, please update in #344.

**Comment by ErikBjorge** [comment]
@kamaitachi522 can you let me know some more about this system as it seems to be very old.  Is chipsec potentially being run in a virtual machine?  I just want to make sure that I am not making a mistake when looking up the device ID.

**Comment by ErikBjorge** [comment]
Chipsec only supports a small number of tests under a virtual environment.  These test check the behavior of the virtual machine and the virtual devices.  Most tests in chipsec are designed to run directly on hardware because it must test the actual register settings.

At this point we do not plan on adding support for specific virtual environments because of the limited use case.

**Comment by ErikBjorge** [comment]
Will not fix at this time due to limited VM use.  If this is an issue please reopen the report.
